=== taljacob2/StockManagementSystem_ex3/SAVED-RSE-V3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="rizpa-stock-exchange-descriptor" type="descriptor"/>

  <xs:element name="rse-buy-orders" type="buyOrders"/>

  <xs:element name="rse-data-base" type="stockDataBase"/>

  <xs:element name="rse-holdings" type="holdings"/>

  <xs:element name="rse-order" type="order"/>

  <xs:element name="rse-sell-orders" type="sellOrders"/>

  <xs:element name="rse-stock" type="stock"/>

  <xs:element name="rse-stock-graph-series" type="stockGraphSeries"/>

  <xs:element name="rse-stocks" type="stocks"/>

  <xs:element name="rse-successfully-finished-transactions" type="transactions"/>

  <xs:element name="rse-transaction" type="transaction"/>

  <xs:element name="rse-user" type="user"/>

  <xs:element name="rse-users" type="users"/>

  <xs:complexType name="descriptor">
    <xs:sequence>
      <xs:element ref="rse-stocks" minOccurs="0"/>
      <xs:element ref="rse-users" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="stocks">
    <xs:complexContent>
      <xs:extension base="engineCollection">
        <xs:sequence>
          <xs:element ref="rse-stock" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="engineCollection">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="stock">
    <xs:sequence>
      <xs:element name="rse-symbol" type="xs:string"/>
      <xs:element name="rse-company-name" type="xs:string"/>
      <xs:element name="rse-price" type="xs:long"/>
      <xs:element ref="rse-data-base" minOccurs="0"/>
      <xs:element ref="rse-stock-graph-series" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="stockDataBase">
    <xs:sequence>
      <xs:element ref="rse-buy-orders" minOccurs="0"/>
      <xs:element ref="rse-sell-orders" minOccurs="0"/>
      <xs:element ref="rse-successfully-finished-transactions" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="buyOrders">
    <xs:complexContent>
      <xs:extension base="engineCollection">
        <xs:sequence>
          <xs:element name="rse-buy-order" type="order" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="order">
    <xs:sequence>
      <xs:element name="time-stamp" type="xs:string"/>
      <xs:element name="order-direction" type="orderDirection"/>
      <xs:element name="order-type" type="orderType"/>
      <xs:element name="quantity" type="xs:long"/>
      <xs:element name="desired-limit-price" type="xs:long"/>
      <xs:element name="requesting-user" type="xs:string" minOccurs="0"/>
      <xs:element name="serialTimeOfRemainedOrder" type="xs:long"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sellOrders">
    <xs:complexContent>
      <xs:extension base="engineCollection">
        <xs:sequence>
          <xs:element name="rse-sell-order" type="order" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="transactions">
    <xs:complexContent>
      <xs:extension base="engineCollection">
        <xs:sequence>
          <xs:element ref="rse-transaction" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="transaction">
    <xs:sequence>
      <xs:element name="time-stamp" type="xs:string"/>
      <xs:element name="quantity" type="xs:long"/>
      <xs:element name="price" type="xs:long"/>
      <xs:element name="buying-user" type="user" minOccurs="0"/>
      <xs:element name="selling-user" type="user" minOccurs="0"/>
      <xs:element name="serialTime" type="xs:long"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="user">
    <xs:sequence>
      <xs:element ref="rse-holdings"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="role" type="userRole" use="required"/>
  </xs:complexType>

  <xs:complexType name="holdings">
    <xs:complexContent>
      <xs:extension base="engineCollection">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="stockGraphSeries">
    <xs:complexContent>
      <xs:extension base="engineCollection">
        <xs:sequence>
          <xs:element name="rse-stock-graph-data" type="simpleEntry" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="simpleEntry">
    <xs:sequence>
      <xs:element name="value" type="xs:anyType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="users">
    <xs:complexContent>
      <xs:extension base="engineCollection">
        <xs:sequence>
          <xs:element ref="rse-user" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="orderDirection">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BUY"/>
      <xs:enumeration value="SELL"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="orderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LMT"/>
      <xs:enumeration value="MKT"/>
      <xs:enumeration value="FOC"/>
      <xs:enumeration value="IOC"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="userRole">
    <xs:restriction base="xs:string">
      <xs:enumeration value="USER"/>
      <xs:enumeration value="ADMIN"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== taljacob2/StockManagementSystem_ex3/downloaded.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<rizpa-stock-exchange-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SAVED-RSE-V3.xsd">
    <rse-stocks>
        <rse-stock>
            <rse-symbol>GOOGL</rse-symbol>
            <rse-company-name>Google</rse-company-name>
            <rse-price>100</rse-price>
            <rse-data-base>
                <rse-buy-orders/>
                <rse-sell-orders/>
                <rse-successfully-finished-transactions/>
            </rse-data-base>
            <rse-stock-graph-series/>
        </rse-stock>
        <rse-stock>
            <rse-symbol>AAPL</rse-symbol>
            <rse-company-name>Apple</rse-company-name>
            <rse-price>75</rse-price>
            <rse-data-base>
                <rse-buy-orders/>
                <rse-sell-orders/>
                <rse-successfully-finished-transactions/>
            </rse-data-base>
            <rse-stock-graph-series/>
        </rse-stock>
        <rse-stock>
            <rse-symbol>MSFT</rse-symbol>
            <rse-company-name>Microsoft</rse-company-name>
            <rse-price>150</rse-price>
            <rse-data-base>
                <rse-buy-orders/>
                <rse-sell-orders/>
                <rse-successfully-finished-transactions/>
            </rse-data-base>
            <rse-stock-graph-series/>
        </rse-stock>
        <rse-stock>
            <rse-symbol>AMZN</rse-symbol>
            <rse-company-name>AMAZON</rse-company-name>
            <rse-price>275</rse-price>
            <rse-data-base>
                <rse-buy-orders/>
                <rse-sell-orders/>
                <rse-successfully-finished-transactions/>
            </rse-data-base>
            <rse-stock-graph-series/>
        </rse-stock>
    </rse-stocks>
    <rse-users>
        <rse-user name="tal" role="USER">
            <rse-holdings/>
        </rse-user>
    </rse-users>
</rizpa-stock-exchange-descriptor>
